In [2]:
from datetime import datetime, timedelta
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like #For solving import pandas_datareader issue
import numpy as np
import datetime
import csv
import requests
import pandas_datareader.data as web
import pandas_datareader as pdr
from pandas_datareader import data, wb

In [5]:
start = datetime.datetime(2022,4,20)
end = datetime.datetime(2022,5,20)

In [6]:
Today = datetime.datetime.now().strftime ("%Y-%m-%d")

# Import list of stock names from NSE website
with requests.Session() as s:
    download = s.get('https://www.nseindia.com/products/content/sec_bhavdata_full.csv')
    decoded_content = download.content.decode('utf-8')
    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = pd.DataFrame(list(cr))
    
#View the top rows
my_list.head()

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,<!DOCTYPE html>,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,"<html lang=""en"">",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,<head>,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,"<meta http-equiv=""Content-Type"" content=""t...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,"<meta http-equiv=""Content-Type"" content=""text/...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [10]:
from nsetools import *
from nsepython import * 
# creating a Nse object
nse = Nse()
 
# nse stock code for wipro
code = "HDFC"
 
# getting stock quote
quote = nse.get_quote(code)
 
# getting base price
value = quote['basePrice']
 
# printing base price
print("Base Price  : " + str(value))
print(nse_index())
print(nse_get_index_list())

Base Price  : 2244.05
       yearLow       last                             indexName   yearHigh  \
0    15,183.40  16,817.55                              NIFTY 50  18,604.45
1    35,018.20  41,932.90                         NIFTY NEXT 50  45,509.70
2    26,186.70  26,778.10                              NIFTY IT  39,446.70
3    32,155.35  37,627.65                            NIFTY BANK  41,840.15
4      12.0800    22.0975                             INDIA VIX    33.9725
..         ...        ...                                   ...        ...
103          -    1189.99  NIFTY BHARAT BOND INDEX - APRIL 2023          -
104          -    1213.34  NIFTY BHARAT BOND INDEX - APRIL 2030          -
105          -    1096.29  NIFTY BHARAT BOND INDEX - APRIL 2025          -
106          -    1103.41  NIFTY BHARAT BOND INDEX - APRIL 2031          -
107          -    5606.22               NIFTY 10 YEAR SDL INDEX          -

    previousClose       high indexType        low                timeVal  \
0       16,858.60  17,026.05        eq  16,788.60  Sep 29, 2022 13:27:22
1       42,083.80  42,699.50        eq  41,858.85  Sep 29, 2022 13:27:22
2       27,067.65  27,300.00        eq  26,721.95  Sep 29, 2022 13:27:22
3       37,759.85  38,283.40        eq  37,545.95  Sep 29, 2022 13:27:22
4         22.0950    22.2875        eq    21.2175  Sep 29, 2022 13:27:22
..            ...        ...       ...        ...                    ...
103             -          -         -          -            28-SEP-2022
104             -          -         -          -            28-SEP-2022
105             -          -         -          -            28-SEP-2022
106             -          -         -          -            28-SEP-2022
107             -          -         -          -            28-SEP-2022

    percChange indexOrder       open indexSubType
0        -0.24       0.00  16,993.60           bm
1        -0.36       1.00  42,463.85           bm
2        -1.07       2.00  27,273.90           sc
3        -0.35       3.00  38,092.85           sc
4         0.01     4.0000    22.0950           bm
..         ...        ...        ...          ...
103          -          -          -            -
104          -          -          -            -
105          -          -          -            -
106          -          -          -            -
107          -          -          -            -

[108 rows x 13 columns]

In [9]:
from nsepython import *
positions = nsefetch('https://www.nseindia.com/api/equity-stockIndices?index=SECURITIES%20IN%20F%26O')
df = pd.DataFrame(positions['data'])
print(df)

         symbol identifier series     open  dayHigh   dayLow lastPrice  \
0           PVR                EQ     1685  1756.55     1685    1747.5
1    ABBOTINDIA                EQ    18260    18999  18222.6     18914
2    JINDALSTEL                EQ   409.15    421.3   409.15     417.4
3       ESCORTS                EQ   2043.5     2134   2043.5    2092.8
4      TATACHEM                EQ     1076     1125  1071.15      1079
..          ...        ...    ...      ...      ...      ...       ...
189    INDIACEM                EQ    252.8    252.8    240.2    241.25
190   INTELLECT                EQ    545.5      547    513.9     513.9
191  ASIANPAINT                EQ  3563.45  3563.45     3405   3412.85
192  LALPATHLAB                EQ   2716.9     2718     2560    2573.4
193    AARTIIND                EQ      780      789   730.55    732.95

    previousClose  change  pChange  ...    nearWKH    nearWKL perChange365d  \
0          1666.4   81.10     4.87  ...  21.100752 -42.763776          4.19
1         18140.2  773.80     4.27  ...  20.975832 -21.915689        -13.66
2          403.75   13.65     3.38  ...  27.760471 -37.212360         11.72
3          2031.4   61.40     3.02  ...   4.438356 -60.159180         36.34
4         1047.95   31.05     2.96  ...   9.631491 -39.522855         15.62
..            ...     ...      ...  ...        ...        ...           ...
189        250.25   -9.00    -3.60  ...  19.300886 -65.864558         31.71
190        535.25  -21.35    -3.99  ...  47.914661   0.000000        -25.16
191       3570.65 -157.80    -4.42  ...   4.934540 -33.314453          5.65
192       2694.35 -120.95    -4.49  ...  34.763100 -42.527208        -26.06
193         781.2  -48.25    -6.18  ...  37.247432  -9.583614        -16.23

     date365dAgo                                      chart365dPath  \
0    28-Sep-2021  https://static.nseindia.com/sparklines/365d/PV...
1    28-Sep-2021  https://static.nseindia.com/sparklines/365d/AB...
2    28-Sep-2021  https://static.nseindia.com/sparklines/365d/JI...
3    28-Sep-2021  https://static.nseindia.com/sparklines/365d/ES...
4    28-Sep-2021  https://static.nseindia.com/sparklines/365d/TA...
..           ...                                                ...
189  28-Sep-2021  https://static.nseindia.com/sparklines/365d/IN...
190  28-Sep-2021  https://static.nseindia.com/sparklines/365d/IN...
191  28-Sep-2021  https://static.nseindia.com/sparklines/365d/AS...
192  28-Sep-2021  https://static.nseindia.com/sparklines/365d/LA...
193  28-Sep-2021  https://static.nseindia.com/sparklines/365d/AA...

      date30dAgo  perChange30d  \
0    29-Aug-2022         -8.31
1    29-Aug-2022         -3.33
2    29-Aug-2022         -2.96
3    29-Aug-2022          4.53
4    29-Aug-2022         -7.46
..           ...           ...
189  29-Aug-2022         15.00
190  29-Aug-2022         -8.10
191  29-Aug-2022          6.80
192  29-Aug-2022          3.73
193  29-Aug-2022         -3.56

                                          chart30dPath  \
0    https://static.nseindia.com/sparklines/30d/PVR...
1    https://static.nseindia.com/sparklines/30d/ABB...
2    https://static.nseindia.com/sparklines/30d/JIN...
3    https://static.nseindia.com/sparklines/30d/ESC...
4    https://static.nseindia.com/sparklines/30d/TAT...
..                                                 ...
189  https://static.nseindia.com/sparklines/30d/IND...
190  https://static.nseindia.com/sparklines/30d/INT...
191  https://static.nseindia.com/sparklines/30d/ASI...
192  https://static.nseindia.com/sparklines/30d/LAL...
193  https://static.nseindia.com/sparklines/30d/AAR...

                                        chartTodayPath  \
0    https://static.nseindia.com/sparklines/today/P...
1    https://static.nseindia.com/sparklines/today/A...
2    https://static.nseindia.com/sparklines/today/J...
3    https://static.nseindia.com/sparklines/today/E...
4    https://static.nseindia.com/sparklines/today/T...
..                                                 ...
189  https://static.nseindia.com/sparklines/today/I...
190  https://static.nseindia.com/sparklines/today/I...
191  https://static.nseindia.com/sparklines/today/A...
192  https://static.nseindia.com/sparklines/today/L...
193  https://static.nseindia.com/sparklines/today/A...

                                                  meta
0    {'symbol': 'PVR', 'companyName': 'PVR Limited'...
1    {'symbol': 'ABBOTINDIA', 'companyName': 'Abbot...
2    {'symbol': 'JINDALSTEL', 'companyName': 'Jinda...
3    {'symbol': 'ESCORTS', 'companyName': 'Escorts ...
4    {'symbol': 'TATACHEM', 'companyName': 'Tata Ch...
..                                                 ...
189  {'symbol': 'INDIACEM', 'companyName': 'The Ind...
190  {'symbol': 'INTELLECT', 'companyName': 'Intell...
191  {'symbol': 'ASIANPAINT', 'companyName': 'Asian...
192  {'symbol': 'LALPATHLAB', 'companyName': 'Dr. L...
193  {'symbol': 'AARTIIND', 'companyName': 'Aarti I...

[194 rows x 25 columns]