In [2]:
from datetime import datetime, timedelta
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like #For solving import pandas_datareader issue
import numpy as np
import datetime
import csv
import requests
import pandas_datareader.data as web
import pandas_datareader as pdr
from pandas_datareader import data, wb

In [5]:
start = datetime.datetime(2022,4,20)
end = datetime.datetime(2022,5,20)

In [6]:
Today = datetime.datetime.now().strftime ("%Y-%m-%d")

# Import list of stock names from NSE website
with requests.Session() as s:
    download = s.get('https://www.nseindia.com/products/content/sec_bhavdata_full.csv')
    decoded_content = download.content.decode('utf-8')
    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = pd.DataFrame(list(cr))
    
#View the top rows
my_list.head()

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,<!DOCTYPE html>,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,"<html lang=""en"">",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,<head>,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,"<meta http-equiv=""Content-Type"" content=""t...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,"<meta http-equiv=""Content-Type"" content=""text/...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [10]:
from nsetools import *
from nsepython import * 
# creating a Nse object
nse = Nse()
 
# nse stock code for wipro
code = "HDFC"
 
# getting stock quote
quote = nse.get_quote(code)
 
# getting base price
value = quote['basePrice']
 
# printing base price
print("Base Price  : " + str(value))
print(nse_index())
print(nse_get_index_list())

Base Price  : 2244.05
       yearLow       last                             indexName   yearHigh  \
0    15,183.40  16,817.55                              NIFTY 50  18,604.45
1    35,018.20  41,932.90                         NIFTY NEXT 50  45,509.70
2    26,186.70  26,778.10                              NIFTY IT  39,446.70
3    32,155.35  37,627.65                            NIFTY BANK  41,840.15
4      12.0800    22.0975                             INDIA VIX    33.9725
..         ...        ...                                   ...        ...
103          -    1189.99  NIFTY BHARAT BOND INDEX - APRIL 2023          -
104          -    1213.34  NIFTY BHARAT BOND INDEX - APRIL 2030          -
105          -    1096.29  NIFTY BHARAT BOND INDEX - APRIL 2025          -
106          -    1103.41  NIFTY BHARAT BOND INDEX - APRIL 2031          -
107          -    5606.22               NIFTY 10 YEAR SDL INDEX          -

    previousClose       high indexType        low                timeVal  \
0       16,858.60  17,026.05        eq  16,788.60  Sep 29, 2022 13:27:22
1       42,083.80  42,699.50        eq  41,858.85  Sep 29, 2022 13:27:22
2       27,067.65  27,300.00        eq  26,721.95  Sep 29, 2022 13:27:22
3       37,759.85  38,283.40        eq  37,545.95  Sep 29, 2022 13:27:22
4         22.0950    22.2875        eq    21.2175  Sep 29, 2022 13:27:22
..            ...        ...       ...        ...                    ...
103             -          -         -          -            28-SEP-2022
104             -          -         -          -            28-SEP-2022
105             -          -         -          -            28-SEP-2022
106             -          -         -          -            28-SEP-2022
107             -          -         -          -            28-SEP-2022

    percChange indexOrder       open indexSubType
0        -0.24       0.00  16,993.60           bm
1        -0.36       1.00  42,463.85           bm
2        -1.07       2.00  27,273.90           sc
3        -0.35       3.00  38,092.85           sc
4         0.01     4.0000    22.0950           bm
..         ...        ...        ...          ...
103          -          -          -            -
104          -          -          -            -
105          -          -          -            -
106          -          -          -            -
107          -          -          -            -

[108 rows x 13 columns]

In [1]:
from nsepython import *
positions = nsefetch('https://www.nseindia.com/api/equity-stockIndices?index=SECURITIES%20IN%20F%26O')
df = pd.DataFrame(positions['data'])
print(df)

         symbol identifier series     open  dayHigh  dayLow lastPrice  \
0        CONCOR                EQ    695.5    711.8   690.1    709.85
1    ASIANPAINT                EQ   3290.5     3360    3274   3347.05
2        HONAUT                EQ  38845.7    39449   38590     39341
3      ADANIENT                EQ  3257.55     3338    3249   3304.05
4      AXISBANK                EQ      780    794.9   774.5    790.25
..          ...        ...    ...      ...      ...     ...       ...
189  AUROPHARMA                EQ   533.05    535.7   517.6     517.8
190  INDUSINDBK                EQ     1215  1215.95  1162.1   1164.65
191  MCDOWELL-N                EQ      861      861   823.1    823.55
192    DIVISLAB                EQ  3705.05  3705.05    3534   3538.15
193    INDIACEM                EQ    272.9    272.9  256.15     259.1

    previousClose  change  pChange  ...    nearWKH     nearWKL perChange365d  \
0          689.95   19.90     2.88  ...   9.226343  -28.131769          0.72
1         3277.95   69.10     2.11  ...   6.767409  -30.744141         -0.88
2         38642.3  698.70     1.81  ...  15.209159  -30.331436        -15.89
3         3246.25   57.80     1.78  ...  14.953668 -141.577100        109.72
4          776.85   13.40     1.72  ...   8.841850  -27.820461         -0.65
..            ...     ...      ...  ...        ...         ...           ...
189        535.45  -17.65    -3.30  ...  30.215633   -4.754198        -25.09
190        1210.3  -45.65    -3.77  ...   8.712181  -52.600891          3.06
191        857.95  -34.40    -4.01  ...  19.255846  -15.667135         -6.17
192        3686.6 -148.45    -4.03  ...  34.781847   -5.128434         -27.3
193        275.25  -16.15    -5.87  ...  13.329988  -78.136817         41.52

     date365dAgo                                      chart365dPath  \
0    08-Oct-2021  https://static.nseindia.com/sparklines/365d/CO...
1    08-Oct-2021  https://static.nseindia.com/sparklines/365d/AS...
2    08-Oct-2021  https://static.nseindia.com/sparklines/365d/HO...
3    08-Oct-2021  https://static.nseindia.com/sparklines/365d/AD...
4    08-Oct-2021  https://static.nseindia.com/sparklines/365d/AX...
..           ...                                                ...
189  08-Oct-2021  https://static.nseindia.com/sparklines/365d/AU...
190  08-Oct-2021  https://static.nseindia.com/sparklines/365d/IN...
191  08-Oct-2021  https://static.nseindia.com/sparklines/365d/MC...
192  08-Oct-2021  https://static.nseindia.com/sparklines/365d/DI...
193  08-Oct-2021  https://static.nseindia.com/sparklines/365d/IN...

      date30dAgo  perChange30d  \
0    09-Sep-2022         -8.34
1    09-Sep-2022         -4.76
2    09-Sep-2022         -7.29
3    09-Sep-2022         -5.94
4    09-Sep-2022         -1.02
..           ...           ...
189  09-Sep-2022         -1.26
190  09-Sep-2022          6.43
191  09-Sep-2022          6.16
192  09-Sep-2022          2.32
193  09-Sep-2022         17.65

                                          chart30dPath  \
0    https://static.nseindia.com/sparklines/30d/CON...
1    https://static.nseindia.com/sparklines/30d/ASI...
2    https://static.nseindia.com/sparklines/30d/HON...
3    https://static.nseindia.com/sparklines/30d/ADA...
4    https://static.nseindia.com/sparklines/30d/AXI...
..                                                 ...
189  https://static.nseindia.com/sparklines/30d/AUR...
190  https://static.nseindia.com/sparklines/30d/IND...
191  https://static.nseindia.com/sparklines/30d/MCD...
192  https://static.nseindia.com/sparklines/30d/DIV...
193  https://static.nseindia.com/sparklines/30d/IND...

                                        chartTodayPath  \
0    https://static.nseindia.com/sparklines/today/C...
1    https://static.nseindia.com/sparklines/today/A...
2    https://static.nseindia.com/sparklines/today/H...
3    https://static.nseindia.com/sparklines/today/A...
4    https://static.nseindia.com/sparklines/today/A...
..                                                 ...
189  https://static.nseindia.com/sparklines/today/A...
190  https://static.nseindia.com/sparklines/today/I...
191  https://static.nseindia.com/sparklines/today/M...
192  https://static.nseindia.com/sparklines/today/D...
193  https://static.nseindia.com/sparklines/today/I...

                                                  meta
0    {'symbol': 'CONCOR', 'companyName': 'Container...
1    {'symbol': 'ASIANPAINT', 'companyName': 'Asian...
2    {'symbol': 'HONAUT', 'companyName': 'Honeywell...
3    {'symbol': 'ADANIENT', 'companyName': 'Adani E...
4    {'symbol': 'AXISBANK', 'companyName': 'Axis Ba...
..                                                 ...
189  {'symbol': 'AUROPHARMA', 'companyName': 'Aurob...
190  {'symbol': 'INDUSINDBK', 'companyName': 'Indus...
191  {'symbol': 'MCDOWELL-N', 'companyName': 'Unite...
192  {'symbol': 'DIVISLAB', 'companyName': 'Divi's ...
193  {'symbol': 'INDIACEM', 'companyName': 'The Ind...

[194 rows x 25 columns]

In [6]:
from nsetools import Nse
from datetime import date
from nsepy import get_history
nse = Nse()
all_stock_codes = nse.get_stock_codes()
for i in all_stock_codes :
    print(i)
    stock = i
    if (stock != 'SYMBOL'):
        nifty_fut = nse.get_quote(stock)
        print (nifty_fut)
# print (all_stock_codes)

SYMBOL

IndexError: list index out of range